### ISSUE TITLE
 login with multiple users in feature file 

### ISSUE THREAD

**Issue by Bibhudattam** [selenium-cucumber/selenium-cucumber-java#18]
How to login with multiple users in feature file ? Can you please explain me through example ?

**Comment by Bibhudattam** [comment]
When I execute with this Feature file. I am getting this error..



Feature: Gmail Login
        As a user I should able to login into Gmail.
 
 Scenario: I login with valid credential
 		Given I navigate to "http://the-internet.herokuapp.com/login"
        And I enter "tomsmith" into input field having id "username"
        And I enter "SuperSecretPassword!" into input field having id "password"
        When I click on element having class "radius"
        Then I should get logged-in
       Then I close browser

  Scenario: I login with valid credential
    Given I navigate to "http://the-internet.herokuapp.com/login"
    And I enter "tomsmith" into input field having id "username"
    And I enter "SuperSecretPassword!" into input field having id "password"
    When I click on element having class "radius"
    Then I should get logged-in
    Then I close browser



Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on port 25096
Only local connections are allowed.
Nov 13, 2017 8:53:54 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on port 23910
Only local connections are allowed.
Nov 13, 2017 8:54:00 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'VCESB03', ip: '192.168.0.154', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver
  at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:131)
  at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
  at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:368)
  at info.seleniumcucumber.methods.NavigateMethods.navigateTo(NavigateMethods.java:23)
  at info.seleniumcucumber.stepdefinitions.PredefinedStepDefinitions.navigate_to(PredefinedStepDefinitions.java:27)
  at ✽.Given I navigate to "http://the-internet.herokuapp.com/login"(E:/Bibhu/devPortal/src/test/resources/features/my_first.feature:13)

Skipped step

Skipped step

Skipped step

Skipped step

Skipped step
URL: data:,
src: <html xmlns="http://www.w3.org/1999/xhtml"><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;"></pre></body></html>
Failed scenarios:
E:/Bibhu/devPortal/src/test/resources/features/my_first.feature:12 # Scenario: I login with valid credential

2 Scenarios (1 failed, 1 passed)
11 Steps (1 failed, 5 skipped, 5 passed)
0m10.486s

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.5.2', revision: '10229a9', time: '2017-08-21T17:29:55.15Z'
System info: host: 'VCESB03', ip: '192.168.0.154', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_121'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:131)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:641)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:368)
	at info.seleniumcucumber.methods.NavigateMethods.navigateTo(NavigateMethods.java:23)
	at info.seleniumcucumber.stepdefinitions.PredefinedStepDefinitions.navigate_to(PredefinedStepDefinitions.java:27)
	at ✽.Given I navigate to "http://the-internet.herokuapp.com/login"(E:/Bibhu/devPortal/src/test/resources/features/my_first.feature:13)

**Comment by sameer49** [comment]
just remove Then I close browser step from scenario

**Comment by sameer49** [comment]
https://github.com/selenium-cucumber/selenium-cucumber-ruby/blob/master/example/desktop%20web/desktop_web_gmail_login/features/gmail_multi_login.feature

**Comment by kumarece** [comment]
How do I close the browser for every scenario and open again ?
